#!/usr/bin/env python3
"""Exercise real consent Activity behavior with deferred authenticator responses."""
import ast,subprocess,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
tree=ast.parse((ROOT/'scripts/test_calendar_account_access.py').read_text())
SOURCES=ast.literal_eval(next(n.value for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='SOURCES' for t in n.targets)))
SOURCES.pop('pl/dudek/extension/calendar/CalendarMicroGAccessActivity.java')
SOURCES.pop('pl/dudek/extension/calendar/AccountAccessTest.java')
SOURCES.update({
'android/os/Bundle.java': '''package android.os;import java.util.*; public class Bundle{Map<String,Object> values=new HashMap<>();public boolean getBoolean(String k,boolean d){return (boolean)values.getOrDefault(k,d);}public void putBoolean(String k,boolean v){values.put(k,v);}public void putString(String k,String v){values.put(k,v);}public String getString(String k){return (String)values.get(k);}}''',
'android/content/Context.java': '''package android.content;import android.content.pm.*;public class Context{public PackageManager getPackageManager(){return new PackageManager();}public String getPackageName(){return "com.google.android.calendar";}public Intent opened;public void startActivity(Intent i){opened=i;}}''',
'android/content/pm/PackageManager.java': '''package android.content.pm;import android.os.Bundle;public class PackageManager{public static final int GET_META_DATA=128;public static boolean installed=true,enabled=true;public static class NameNotFoundException extends Exception{}public static class ApplicationInfo{public Bundle metaData;}public ApplicationInfo getApplicationInfo(String name,int flags)throws NameNotFoundException{if(name.equals("app.revanced.android.gms")&&!installed)throw new NameNotFoundException();var i=new ApplicationInfo();i.metaData=new Bundle();if(enabled)i.metaData.putString("app.revanced.MICROG_PACKAGE_NAME","app.revanced.android.gms");return i;}}''',
'android/content/ComponentName.java': '''package android.content;public class ComponentName{public String name;public ComponentName(Context c,String n){name=n;}public ComponentName(Context c,Class<?> n){name=n.getName();}}''',
'android/content/Intent.java': '''package android.content;import java.util.*;public class Intent{public static final int FLAG_ACTIVITY_NEW_TASK=268435456;public String action="original",data="event";public int flags=42;public Map<String,String> extras=new HashMap<>();public ComponentName component;public Intent(){}public Intent(Context c,Class<?> n){component=new ComponentName(c,n);}public Intent(Intent i){action=i.action;data=i.data;flags=i.flags;extras.putAll(i.extras);component=i.component;}public Intent setComponent(ComponentName c){component=c;return this;}public Intent addFlags(int v){flags|=v;return this;}public String getStringExtra(String k){return extras.get(k);}}''',
'android/app/Activity.java': '''package android.app;import android.content.*;import android.os.*;public class Activity extends Context{public static final int RESULT_OK=-1,RESULT_CANCELED=0;public Intent source=new Intent(),chooser;public int request,starts,finishes;public Object retained;protected void onCreate(Bundle b){}protected void onDestroy(){}protected void onSaveInstanceState(Bundle b){}protected void onActivityResult(int q,int r,Intent i){}public Object getLastNonConfigurationInstance(){return retained;}public Object onRetainNonConfigurationInstance(){return null;}public Intent getIntent(){return source;}public void startActivityForResult(Intent i,int r){chooser=i;request=r;}@Override public void startActivity(Intent i){opened=i;starts++;}public void finish(){finishes++;}public boolean isFinishing(){return finishes>0;}}''',
'android/view/View.java': '''package android.view;import android.content.Context;public class View{Context c;public View(Context c){this.c=c;}public Context getContext(){return c;}}''',
'android/accounts/Account.java': '''package android.accounts;import java.util.Objects;public class Account{public final String name,type;public Account(String n,String t){name=n;type=t;}public boolean equals(Object o){return o instanceof Account a&&a.name.equals(name)&&a.type.equals(type);}public int hashCode(){return Objects.hash(name,type);}}''',
'android/accounts/AccountManagerFuture.java': '''package android.accounts;public interface AccountManagerFuture<T>{T getResult()throws Exception;}''',
'android/accounts/AccountManagerCallback.java': '''package android.accounts;public interface AccountManagerCallback<T>{void run(AccountManagerFuture<T> future);}''',
'android/accounts/AuthenticatorException.java': '''package android.accounts;public class AuthenticatorException extends Exception{}''',
'android/accounts/AccountManager.java': '''package android.accounts;import android.app.Activity;import android.content.*;import android.os.*;import java.util.*;public class AccountManager{public static final String KEY_ACCOUNT_NAME="authAccount",KEY_ACCOUNT_TYPE="accountType",KEY_AUTHTOKEN="authtoken";public static Account[] google,microg;public static int requests,choosers;public static List<Account> allowed;public static Account last;public static AccountManagerCallback<Bundle> pending;public static AccountManager get(Context c){return new AccountManager();}public Account[] getAccountsByType(String t){return t.equals("com.google")?google:microg;}public static Intent newChooseAccountIntent(Account a,List<Account> b,String[] types,String d,String e,String[] f,Bundle g){if(!types[0].equals("app.revanced"))throw new AssertionError();allowed=b;choosers++;return new Intent();}public AccountManagerFuture<Bundle> getAuthToken(Account a,String scope,Bundle options,Activity activity,AccountManagerCallback<Bundle> cb,Object handler){if(!scope.equals("oauth2:https://www.googleapis.com/auth/calendar")||activity==null)throw new AssertionError();last=a;requests++;pending=cb;return ()->null;}public static void respond(String token,boolean failure){var cb=pending;cb.run(()->{if(failure)throw new AuthenticatorException();Bundle b=new Bundle();b.putString(KEY_AUTHTOKEN,token);return b;});}}''',
'android/content/ContentResolver.java': '''package android.content;import android.accounts.Account;import android.os.Bundle;import java.util.*;public class ContentResolver{public static final String SYNC_EXTRAS_MANUAL="force";public static List<String> authorities=new ArrayList<>();public static void requestSync(Account a,String authority,Bundle b){if(!a.type.equals("com.google")||!a.name.equals("test-account")||!b.getBoolean(SYNC_EXTRAS_MANUAL,false))throw new AssertionError();authorities.add(authority);}}''',
'android/widget/Toast.java': '''package android.widget;import android.content.*;public class Toast{public static final int LENGTH_LONG=1;public static String last;public static Toast makeText(Context c,String t,int l){last=t;return new Toast();}public void show(){}}''',
'pl/dudek/extension/calendar/MicroGAccessTest.java': '''package pl.dudek.extension.calendar;import android.accounts.*;import android.content.*;import android.content.pm.PackageManager;import android.os.Bundle;import android.view.View;import android.widget.Toast;
public class MicroGAccessTest{
static void check(boolean v){if(!v)throw new AssertionError();}static Account account(){return new Account("test-account","app.revanced");}
static void reset(){AccountManager.google=new Account[]{new Account("test-account","com.google")};AccountManager.microg=new Account[]{account()};AccountManager.requests=AccountManager.choosers=0;AccountManager.pending=null;PackageManager.installed=PackageManager.enabled=true;ContentResolver.authorities.clear();Toast.last=null;}
static CalendarMicroGAccessActivity fresh(){var a=new CalendarMicroGAccessActivity();a.source.extras.put("event","preserve");return a;}
static void success(CalendarMicroGAccessActivity a){check(a.starts==1&&a.finishes==1);check(a.opened.component.name.equals("com.android.calendar.event.LaunchInfoActivity"));check(a.opened.extras.equals(a.source.extras)&&a.opened.data.equals(a.source.data)&&a.opened.flags==a.source.flags);check(ContentResolver.authorities.equals(java.util.List.of("com.android.calendar","com.google.android.calendar")));check(!Toast.last.contains("secret-token"));}
public static void main(String[] args){
reset();var a=fresh();a.onCreate(null);check(AccountManager.requests==1&&a.starts==0&&a.finishes==0);AccountManager.respond("secret-token",false);success(a);
reset();a=fresh();a.onCreate(null);AccountManager.respond("",false);check(a.starts==1&&a.finishes==1&&ContentResolver.authorities.isEmpty());
reset();a=fresh();a.onCreate(null);AccountManager.respond(null,true);check(a.starts==1&&a.finishes==1&&Toast.last.endsWith("AuthenticatorException"));
reset();a=fresh();a.onCreate(null);Object retained=a.onRetainNonConfigurationInstance();a.onDestroy();var rotated=fresh();rotated.retained=retained;rotated.onCreate(null);check(AccountManager.requests==1);AccountManager.respond("secret-token",false);success(rotated);check(a.starts==0);
reset();a=fresh();a.onCreate(null);retained=a.onRetainNonConfigurationInstance();a.onDestroy();AccountManager.respond("secret-token",false);rotated=fresh();rotated.retained=retained;rotated.onCreate(null);success(rotated);check(AccountManager.requests==1);
reset();AccountManager.microg=new Account[0];a=fresh();a.onCreate(null);check(AccountManager.requests==0&&AccountManager.choosers==1&&AccountManager.allowed.equals(java.util.List.of(account())));Intent result=new Intent();result.extras.put("authAccount","test-account");result.extras.put("accountType","app.revanced");AccountManager.microg=new Account[]{account()};a.onActivityResult(a.request,-1,result);check(AccountManager.requests==1);AccountManager.respond("secret-token",false);success(a);
reset();AccountManager.microg=new Account[0];a=fresh();a.onCreate(null);a.onActivityResult(a.request,-1,new Intent());check(AccountManager.requests==0&&a.finishes==1);
reset();AccountManager.microg=new Account[0];a=fresh();a.onCreate(null);a.onActivityResult(a.request,0,null);check(AccountManager.requests==0&&a.finishes==1);
reset();PackageManager.installed=false;a=fresh();a.onCreate(null);check(AccountManager.requests==0&&a.finishes==1&&Toast.last.contains("7.1.1"));
reset();a=fresh();check(CalendarMicroGAccessActivity.launchIfEnabled(a,a.source));check(a.opened.component.name.endsWith("CalendarMicroGAccessActivity")&&a.opened.extras.equals(a.source.extras));PackageManager.enabled=false;a=fresh();check(!CalendarMicroGAccessActivity.launchIfEnabled(a,a.source)&&a.starts==0);
reset();a=fresh();CalendarMicroGAccessActivity.signIn(new View(a));check(a.opened.component.name.endsWith("CalendarMicroGAccessActivity"));
System.out.println("PASS: actual consent request, deferred success/failure/empty token, account visibility/matching, cancellation, rotation, native payload and genuine sync requests");}}
'''
})
with tempfile.TemporaryDirectory(prefix='calendar-microg-access-') as tmp:
    directory=Path(tmp)
    for name,content in SOURCES.items():
        path=directory/name;path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
    production=ROOT/'extensions/calendar/src/main/java/pl/dudek/extension/calendar/CalendarMicroGAccessActivity.java'
    subprocess.run(['javac','-d',str(directory),*map(str,directory.rglob('*.java')),str(production)],check=True)
    subprocess.run(['java','-cp',str(directory),'pl.dudek.extension.calendar.MicroGAccessTest'],check=True)
